### ISSUE TITLE
scripts库版本问题

### ISSUE THREAD

**Issue by wordmeng** [yunwei37/COVID-19-NLP-vis#3]
已经解决

**Comment by jiaoleixin** [comment]
您好，不知您怎么知道我遇到过此问题（我并未issue）😅不过您所写的各视图实现的Python文件在scripts目录下，这似乎会因为与Python内置库冲突而导致引入错误。希望您可以在后续版本迭代中修改scripts名称。谢谢。by Leixin-------- 原始邮件 --------发件人： wordmeng <notifications@github.com>日期： 2020年12月14日周一 15:28收件人： yunwei37/COVID-19-NLP-vis <COVID-19-NLP-vis@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [yunwei37/COVID-19-NLP-vis] scripts库版本问题 (#3)

大佬，您好。目前scripts库默认安装已经是2.0版本，请问您所使用是哪个版本，谢谢啦

**Comment by yunwei37** [comment]
This is fix now.
