### ISSUE TITLE
您好，可以请您提供一下数据集吗

### ISSUE THREAD

**Issue by ChuXi-2024** [yunwei37/COVID-19-NLP-vis#4]
作者您好！抱歉打扰了。我最近也想尝试做新冠疫情相关的nlp，您的新冠肺炎nlp项目的数据集可以向我提供一下吗？我的邮箱1207588952@qq.com

**Comment by FujinomiyaNeko981213** [comment]
我也需要数据集，如果您有可以发我邮箱吗839882347@qq.com
