### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by FujinomiyaNeko981213** [yunwei37/COVID-19-NLP-vis#5]
您好，我在研究疫情分析时查到了您的开源项目，在试着运行之后虽然网页可以正常打开但是有些部分仍然会报运行错误，比如在传输某个数据时提示并不支持ZIP格式，应该转化成list但源码有点一知半解
错误提示：File "C:\Users\83988\Desktop\代码\COVID-19-NLP-vis-master\COVID-19-NLP-vis-master\scripts\mapchina.py", line 92, in render_mapcountChina_current
    Map()
  File "E:\Python files\lib\site-packages\pyecharts\charts\basic_charts\map.py", line 44, in add
    if isinstance(data_pair[0], opts.MapItem):
TypeError: 'zip' object is not subscriptable

**Comment by yunwei37** [comment]
这里的报错信息有点太少了...如果能给我完整的报错信息我可以看看...

**Comment by marshcoldboy** [comment]
使用list包装zip对象，如下：
list(zip())
即可解决TypeError: ‘zip‘ object is not subscriptable。

**Comment by yunwei37** [comment]
可以帮忙提个 pr 嘛?多谢啦
